<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="/css/common.css" type="text/css" media="screen">
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>
</head>
<body>
	<?=$this->layout()->content?>
	<div id="mask"></div>
</body>
</html>