<div class="row">
    <div class="col-lg-5 well">
        <form class="form-signin" name="auth" method="post" action="<?=$this->url(array(), 'auth')?>" id="authForm" onsubmit="submitAuth(event); return false;">
        <div class="login-screen">
            <div class="login-form">

                <?=$this->FormErrors($this->form)?>

                <?=$this->ElementsErrors($this->form)?>

                <div class="form-group">
                    <input name="login" type="text" id="inputLogin" placeholder="Логин" value="<?= $this->form->login->getValue() ?>" class="form-control"  autocomplete="off">
                    <i class="login-field-icon fa fa-user"></i>
                </div>

                <div class="form-group">
                    <input name="password" type="password" id="inputPass" placeholder="Пароль" value="" class="form-control" autocomplete="off">
                    <i class="login-field-icon fa fa-lock"></i>
                </div>


                <button type="submit" class="authSubmit btn btn-info btn-large btn-block">Войти</button>

                <!--a href="/recover_password" class="login-link">Забыли пароль?</a-->
            </div>
        </div>
        </form>
    </div>
</div>

<script type="text/javascript">
	function submitAuth (e) {
		if ($(e.explicitOriginalTarget).attr('id') == "inputLogin" && $('#inputPass').text() == "") {
			$('#inputPass').focus();
			return false;
		} else {
			document.getElementById('authForm').submit();
		}
	}

	$(function(){
		$('#inputLogin').focus();
		$('#mask').hide();
	});
</script>
