<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="/css/common.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen">
	<?php echo $this->headLink(); ?>
	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen" />
	<?php echo $this->headScript(); ?>
	<script type="text/javascript" src="/js/bootstrap.min.js" ></script>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>
</head>
<body>
<div class="maw960" id="header">
	<h1>:(</h1>
</div>
<div class="maw960">
	<div class="alert">
		<h2>404</h2>
		<h3>Страница не найдена</h3>

		<p><?=$this->text?></p>

	    <b>Возможные причины</b>
		<ol>
			<li>
				при вводе в строку адреса браузера была допущена опечатка,
			</li>
			<li>
			    ссылка, ведущая на страницу, устаревшая или не корректная,
			</li>
			<li>
			    страница была удалена.
			</li>
		</ol>

	    <b>Возможные решения</b>
		<ol>
			<li>
				попытаться исправить ошибку ввода неправильного адреса данной страницы
			</li>
			<li>
			    сообщить нашей службе поддержки об этом инциденте
			</li>
			<li>
			    Перейти на <a href="/">главную страницу</a>
			</li>
		</ol>
	</div>
</div>
<div id="footer"></div>
</body>
</html>