<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="/css/common.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen">
	<?php echo $this->headLink(); ?>
	<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" media="screen" />
	<?php echo $this->headScript(); ?>
	<script type="text/javascript" src="/js/bootstrap.min.js" ></script>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>
</head>
<body>
<div class="maw960" id="header">
	<h1><span class="">Информационная система</span><img src="/images/nzsh.gif" alt="Наша Здоровая Школа"></h1>
</div>
<div class="maw960">
	<div class="alert">
	  <h4>Извините, пожалуйста, за доставленные неудобства.</h4>
	  <p>
	      В системе произошла непредвиденная ошибка.
	  </p>
	</div>
</div>
<div id="footer"></div>
</body>
</html>
